# Generated by Django 5.1.4 on 2024-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_player_is_staff_alter_player_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.CharField(choices=[('no_league', 'No League'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('master', 'Master')], default='no_league', max_length=10, verbose_name='League'),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
