# Generated by Django 5.1.4 on 2024-12-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score (XP)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
