# Generated by Django 5.1.4 on 2024-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_score_quiz_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score (XP)'),
        ),
    ]
